@startuml 夕食を作る
start
fork
  :スーパーに買い出し
  30分
  担当者 太郎;
fork again
  :ご飯をたく
  1時間
  担当者 次郎;
end fork
fork
  :サンマに塩を振る
  1分
  担当者 次郎;
  :サンマを焼く
  1分
  担当者 次郎;
fork again
  :ほうれん草の茹でる
  10分
  担当者 花子;
  :かつおぶしと醬油をかける
  1分
  担当者 花子;
 fork again
  :しいたけを切る
  2分
  担当者 太郎;
  :だし汁をあたためる
  5分
  担当者 太郎;
  :だし汁にといた卵を入れる
  1分
  担当者 太郎;
end fork
fork
 :食べる
  担当者 太郎、花子、次郎;
end fork
stop
@enduml
